# Generated by Django 2.2.6 on 2019-11-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20191105_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
